<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Estimación | Fundamentos de Investigación II</title>
  <meta name="description" content="Apuntes de la asignatura de Fundamentos de Investigación II" />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Estimación | Fundamentos de Investigación II" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/cover.png" />
  <meta property="og:description" content="Apuntes de la asignatura de Fundamentos de Investigación II" />
  <meta name="github-repo" content="negatoscope/FdI2" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Estimación | Fundamentos de Investigación II" />
  
  <meta name="twitter:description" content="Apuntes de la asignatura de Fundamentos de Investigación II" />
  <meta name="twitter:image" content="images/cover.png" />

<meta name="author" content="Luis Eudave" />


<meta name="date" content="2020-10-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probability.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />










<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Fundamentos de Investigación II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>1</b> Introducción a la probabilidad</a><ul>
<li class="chapter" data-level="1.1" data-path="probability.html"><a href="probability.html#probstats"><i class="fa fa-check"></i><b>1.1</b> ¿Cómo de diferentes son la probabilidad y la estadística?</a></li>
<li class="chapter" data-level="1.2" data-path="probability.html"><a href="probability.html#probmeaning"><i class="fa fa-check"></i><b>1.2</b> ¿Qué significa la probabilidad?</a><ul>
<li class="chapter" data-level="1.2.1" data-path="probability.html"><a href="probability.html#la-vision-frecuentista"><i class="fa fa-check"></i><b>1.2.1</b> La visión frecuentista</a></li>
<li class="chapter" data-level="1.2.2" data-path="probability.html"><a href="probability.html#la-vision-bayesiana"><i class="fa fa-check"></i><b>1.2.2</b> La visión bayesiana</a></li>
<li class="chapter" data-level="1.2.3" data-path="probability.html"><a href="probability.html#cual-es-la-diferencia-y-quien-tiene-razon"><i class="fa fa-check"></i><b>1.2.3</b> ¿Cuál es la diferencia? ¿Y quién tiene razón?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="probability.html"><a href="probability.html#basicprobability"><i class="fa fa-check"></i><b>1.3</b> Teoría de probabilidad básica</a><ul>
<li class="chapter" data-level="1.3.1" data-path="probability.html"><a href="probability.html#introduccion-a-las-distribuciones-de-probabilidad"><i class="fa fa-check"></i><b>1.3.1</b> Introducción a las distribuciones de probabilidad</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="probability.html"><a href="probability.html#binomial"><i class="fa fa-check"></i><b>1.4</b> La distribución binomial</a><ul>
<li class="chapter" data-level="1.4.1" data-path="probability.html"><a href="probability.html#introduccion-al-binomio"><i class="fa fa-check"></i><b>1.4.1</b> Introducción al binomio</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="probability.html"><a href="probability.html#normal"><i class="fa fa-check"></i><b>1.5</b> La distribución normal</a><ul>
<li class="chapter" data-level="1.5.1" data-path="probability.html"><a href="probability.html#density"><i class="fa fa-check"></i><b>1.5.1</b> Densidad de probabilidad</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="probability.html"><a href="probability.html#otherdists"><i class="fa fa-check"></i><b>1.6</b> Otras distribuciones útiles</a></li>
<li class="chapter" data-level="1.7" data-path="probability.html"><a href="probability.html#resumen"><i class="fa fa-check"></i><b>1.7</b> Resumen</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>2</b> Estimación</a><ul>
<li class="chapter" data-level="2.1" data-path="estimation.html"><a href="estimation.html#srs"><i class="fa fa-check"></i><b>2.1</b> Muestras, poblaciones y muestreo</a><ul>
<li class="chapter" data-level="2.1.1" data-path="estimation.html"><a href="estimation.html#pop"><i class="fa fa-check"></i><b>2.1.1</b> Definición de una población</a></li>
<li class="chapter" data-level="2.1.2" data-path="estimation.html"><a href="estimation.html#muestras-aleatorias-simples"><i class="fa fa-check"></i><b>2.1.2</b> Muestras aleatorias simples</a></li>
<li class="chapter" data-level="2.1.3" data-path="estimation.html"><a href="estimation.html#la-mayoria-de-las-muestras-no-son-muestras-aleatorias-simples"><i class="fa fa-check"></i><b>2.1.3</b> La mayoría de las muestras no son muestras aleatorias simples</a></li>
<li class="chapter" data-level="2.1.4" data-path="estimation.html"><a href="estimation.html#cuanto-importa-si-no-se-tiene-una-muestra-aleatoria-simple"><i class="fa fa-check"></i><b>2.1.4</b> ¿Cuánto importa si no se tiene una muestra aleatoria simple?</a></li>
<li class="chapter" data-level="2.1.5" data-path="estimation.html"><a href="estimation.html#parametros-poblacionales-y-estadisticos-muestrales"><i class="fa fa-check"></i><b>2.1.5</b> Parámetros poblacionales y estadísticos muestrales</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="estimation.html"><a href="estimation.html#lawlargenumbers"><i class="fa fa-check"></i><b>2.2</b> La ley de los grandes números</a></li>
<li class="chapter" data-level="2.3" data-path="estimation.html"><a href="estimation.html#samplesandclt"><i class="fa fa-check"></i><b>2.3</b> Distribuciones muestrales y el teorema del límite central</a><ul>
<li class="chapter" data-level="2.3.1" data-path="estimation.html"><a href="estimation.html#samplingdists"><i class="fa fa-check"></i><b>2.3.1</b> Distribución muestral de la media</a></li>
<li class="chapter" data-level="2.3.2" data-path="estimation.html"><a href="estimation.html#existen-distribuciones-muestrales-para-cualquier-estadistico-muestral"><i class="fa fa-check"></i><b>2.3.2</b> Existen distribuciones muestrales para cualquier estadístico muestral</a></li>
<li class="chapter" data-level="2.3.3" data-path="estimation.html"><a href="estimation.html#clt"><i class="fa fa-check"></i><b>2.3.3</b> El teorema del límite central</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="estimation.html"><a href="estimation.html#pointestimates"><i class="fa fa-check"></i><b>2.4</b> Estimando parámetros poblacionales</a><ul>
<li class="chapter" data-level="2.4.1" data-path="estimation.html"><a href="estimation.html#estimando-la-media-poblacional"><i class="fa fa-check"></i><b>2.4.1</b> Estimando la media poblacional</a></li>
<li class="chapter" data-level="2.4.2" data-path="estimation.html"><a href="estimation.html#estimando-la-desviacion-estandar-poblacional"><i class="fa fa-check"></i><b>2.4.2</b> Estimando la desviación estándar poblacional</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="estimation.html"><a href="estimation.html#ci"><i class="fa fa-check"></i><b>2.5</b> Estimando un intervalo de confianza</a><ul>
<li class="chapter" data-level="2.5.1" data-path="estimation.html"><a href="estimation.html#que-pasa-cuando-no-conocemos-los-parametros-poblacionales"><i class="fa fa-check"></i><b>2.5.1</b> ¿Qué pasa cuando no conocemos los parámetros poblacionales?</a></li>
<li class="chapter" data-level="2.5.2" data-path="estimation.html"><a href="estimation.html#interpretando-un-intervalo-de-confianza"><i class="fa fa-check"></i><b>2.5.2</b> Interpretando un intervalo de confianza</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="estimation.html"><a href="estimation.html#samplesize"><i class="fa fa-check"></i><b>2.6</b> Estimando el tamaño muestral</a></li>
<li class="chapter" data-level="2.7" data-path="estimation.html"><a href="estimation.html#resumen-1"><i class="fa fa-check"></i><b>2.7</b> Resumen</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fundamentos de Investigación II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimation" class="section level1">
<h1><span class="header-section-number">Capítulo 2</span> Estimación</h1>
<p>Al comienzo del capítulo inicial, vimos la distinción que existe entre la <em>estadística descriptiva</em> y la <em>estadística inferencial</em>. El papel de la estadística descriptiva es resumir de manera concisa lo que <em>ya sabemos</em>. Por otro lado, el propósito de la estadística inferencial es “aprender lo que no sabemos a partir de lo que hacemos”. Ahora que tenemos cierto conocimiento sobre la teoría de la probabilidad, podemos pensar en el problema de la inferencia estadística. ¿Qué tipo de información nos gustaría conocer o aprender? ¿Y cómo lo aprendemos? Estas son las preguntas que se encuentran en el corazón de la estadística inferencial y tradicionalmente se dividen en dos “grandes ideas”: la estimación y la prueba o contraste de hipótesis. El objetivo de este capítulo es presentar la primera de estas grandes ideas, la teoría de la estimación. Pero antes, hablaré sobre la teoría del muestreo, ya que la teoría de la estimación no tiene sentido hasta que no se comprende el muestreo. Como consecuencia, este capítulo se divide en dos partes, las secciones <a href="estimation.html#srs">2.1</a> a <a href="estimation.html#samplesandclt">2.3</a> se centran en la teoría del muestreo, y las secciones <a href="estimation.html#pointestimates">2.4</a> y <a href="estimation.html#ci">2.5</a> hacen uso de esa teoría del muestreo para discutir cómo piensan los estadísticos sobre la estimación.</p>
<div id="srs" class="section level2">
<h2><span class="header-section-number">2.1</span> Muestras, poblaciones y muestreo</h2>
<p>Antes hemos hablado sobre el proceso de inducción inferencial, donde recalcamos que <em>todo</em> aprendizaje (o aquello que queremos llegar a conocer) requiere que hagamos suposiciones. Aceptando que esto es cierto, hemos de aceptar algunas suposiciones generales sobre los datos que hemos adquirido para poder utilizarlos. Aquí es donde entra en juego la <strong><em>teoría del muestreo</em></strong>. Si la teoría de la probabilidad representa los cimientos sobre los que se construye toda la teoría estadística, la teoría del muestreo es el marco alrededor del cual se puede construir el resto de la casa. La teoría del muestreo juega un papel muy importante en la especificación de los supuestos en los que se basan sus inferencias estadísticas. Y para hablar sobre “hacer inferencias” de la forma en que los estadísticos lo piensan, debemos ser un poco más explícitos acerca de <em>qué</em> es lo que estamos extrayendo (la muestra) y <em>sobre qué</em> es de lo que estamos haciendo inferencias (la población).</p>
<p>En casi todas las situaciones de interés, lo que tenemos a nuestra disposición como investigadores es una <em>muestra</em> de datos. Podríamos, por ejemplo, haber realizado un experimento con un cierto número de participantes; una empresa de encuestas podría haber telefoneado a algunas personas para hacer preguntas sobre las intenciones de voto, etc. Independientemente de cual sea el caso, el conjunto de datos disponibles que tengamos es finito e incompleto. No podemos conseguir que todas las personas del mundo realicen nuestro experimento; una empresa de encuestas no tiene el tiempo ni el dinero para llamar a todos los votantes del país, etc. Para la estadística descriptiva esta muestra es lo único que importa. Con la estadística inferencial daremos un paso más allá.</p>
<div id="pop" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Definición de una población</h3>
<p>Una muestra es una cosa muy concreta. Puedes abrir un archivo de Excel y ahí podrás encontrar los datos de una muestra. Una <strong><em>población</em></strong>, por otro lado, es una idea más abstracta. Se refiere al conjunto de todas las personas posibles, o todas las observaciones posibles, sobre las que desea sacar conclusiones y, en general, es <em>mucho</em> más grande que la muestra. En un mundo ideal, el investigador comenzaría el estudio con una idea clara de cuál es la población de interés, ya que el proceso de diseñar un estudio y probar una hipótesis sobre los datos que produce depende de la población sobre la que se quiere hacer afirmaciones. Sin embargo, en la práctica esto no sucede siempre: por lo general, el investigador tiene una idea bastante vaga de lo que es la población y diseña el estudio lo mejor que puede sobre esa base.</p>
<p>A veces es fácil indicar cuál es la población de interés. En el ejemplo de la “empresa de encuestas” que vimos en el capítulo anterior, la población consistía en todos los votantes inscritos en un momento del estudio: varios millones de personas. En cambio, la muestra fue un conjunto de 1,000 personas que pertenecen todas a esa población. Sin embargo, en la mayoría de los casos, definir esta muestra/población no es tan fácil. En estudios o experimentos con seres humanos, determinar la población de interés es un poco más complicado. Supongamos que realizo un experimento con 100 estudiantes de pregrado que representan mi muestra. Mi objetivo es, por ejemplo, intentar aprender algo sobre cómo una intervención educativa modifica la dinámica de una clase. Tomando en cuento a la muestra que tenemos, ¿cuál de las siguientes opciones contará como “la población”?:</p>
<ul>
<li>¿Todos los estudiantes de educación de la Universidad de Navarra?<br />
</li>
<li>¿Estudiantes de grado en educación en general, de cualquier parte del mundo?<br />
</li>
<li>¿Españoles vivos actualmente?<br />
</li>
<li>¿Españoles de edades similares a las de mi muestra?</li>
<li>¿Hispanoparlantes?</li>
<li>¿Cualquier persona viva actualmente?<br />
</li>
<li>¿Cualquier ser humano, pasado, presente o futuro?</li>
</ul>
<p>Cada una de estas opciones define un grupo real de personas, las cuales podrían ser todas de interés para mí como investigador en educación, y no es tan obvio cuál debería ser la verdadera población de interés.</p>
</div>
<div id="muestras-aleatorias-simples" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Muestras aleatorias simples</h3>
<div class="figure"><span id="fig:srs1"></span>
<img src="img/estimation/srs1.png" alt="Muestreo aleatorio simple *sin* reemplazo de una población finita." width="463" />
<p class="caption">
Figure 2.1: Muestreo aleatorio simple <em>sin</em> reemplazo de una población finita.
</p>
</div>
<p>Independientemente de cómo definamos a una población, la clave es que la muestra es un subgrupo de esa población, y nuestro objetivo es utilizar nuestro conocimiento de la muestra para hacer inferencias sobre las propiedades de la población. La relación que exista entre los dos dependerá del <em>procedimiento</em> mediante el cual se seleccionó la muestra. Este procedimiento se conoce como <strong><em>método de muestreo</em></strong> y es importante comprender su importancia.</p>
<p>Pongamos un ejemplo sencillo. Imaginemos que tenemos una bolsa que contiene 10 fichas. Cada ficha tiene una letra única impresa, con la que la podemos distinguir de entre las otras 10 fichas. Las fichas vienen en dos colores, blanco y negro. Este conjunto de fichas es la población de interés y se muestra gráficamente a la izquierda de la Figura <a href="estimation.html#fig:srs1">2.1</a>. Como podrás ver en la imagen, tenemos 4 fichas negras y 6 fichas blancas, pero recuerda que en la vida real esto no lo sabríamos a menos que miráramos en la bolsa. Ahora imagina que realizas el siguiente “experimento”: agitas la bolsa, cierras los ojos y sacas 4 fichas sin devolver ninguna de ellas a la bolsa. Primero sale la ficha <span class="math inline">\(a\)</span> (negra), seguida de la ficha <span class="math inline">\(c\)</span> (blanca), luego la <span class="math inline">\(j\)</span> (blanca) y finalmente la ficha <span class="math inline">\(b\)</span> (negra). Una vez extraídas 4 fichas, podrás volver a poner todas las fichas en la bolsa y repetir el experimento, como se muestra en el lado derecho de la Figura <a href="estimation.html#fig:srs1">2.1</a>. Cada vez que repites el experimento obtienes resultados diferentes, pero el procedimiento es idéntico en cada caso. El hecho de que el mismo procedimiento pueda dar lugar a resultados diferentes cada vez, lo define como un proceso <em>aleatorio</em>. Y debido a que hemos agitado la bolsa antes de sacar las fichas, parece razonable pensar que todas las fichas tienen las mismas posibilidades de ser seleccionadas. Un procedimiento en el que todos los miembros de la población tienen las mismas posibilidades de ser seleccionados se denomina <strong><em>muestra aleatoria simple</em></strong>. El hecho de que se <em>no</em> se devuelvan las fichas a la bolsa después de salir, significa que no podremos observar la misma ficha dos veces, y en tales casos se dice que ha habido un muestreo <strong><em>sin reemplazo</em></strong>.</p>
<p>Para comprender la importancia del procedimiento de muestreo, consideremos ahora una forma alternativa en la que podría haberse realizado el experimento. Supongamos que mi sobrino de 3 años coge la bolsa y decide sacar las cuatro fichas negras (le gusta el color negro) sin devolverlas la bolsa. Este esquema de muestreo <em>sesgado</em> se muestra en la Figura <a href="estimation.html#fig:brs">2.2</a>. Ahora considera el valor que tiene obtener una muestra con 4 fichas negras y 0 fichas blancas siguiendo el procedimiento de mi sobrino. Vemos pues, como el valor dependerá mucho del método de muestreo. Si sabemos que el método de muestreo está sesgado para seleccionar únicamente fichas negras, entonces una muestra que consta únicamente de fichas negras no dice mucho sobre nuestra población de fichas. Por esta razón, los estadísticos prefieren que un conjunto de datos provenga de una muestra aleatoria simple, ya que facilita <em>mucho</em> el análisis de los datos.</p>
<div class="figure"><span id="fig:brs"></span>
<img src="img/estimation/brs.png" alt="Muestreo sesgado sin reemplazo de una población finita." width="461" />
<p class="caption">
Figure 2.2: Muestreo sesgado sin reemplazo de una población finita.
</p>
</div>
<div class="figure"><span id="fig:srs2"></span>
<img src="img/estimation/srs2.png" alt="Muestreo aleatorio simple *con* reemplazo de una población finita." width="466" />
<p class="caption">
Figure 2.3: Muestreo aleatorio simple <em>con</em> reemplazo de una población finita.
</p>
</div>
<p>Vale la pena mencionar un tercer procedimiento. Esta vez cerramos los ojos, agitamos la bolsa y sacamos una ficha. Sin embargo, esta vez registramos la observación y luego volvemos a poner la ficha dentro de la bolsa. Nuevamente, cerramos los ojos, agitamos la bolsa y sacamos otra ficha. Repetimos este procedimiento hasta que tengamos 4 fichas. Los conjuntos de datos que hemos generado de esta manera siguen siendo muestras aleatorias simples, pero debido a que volvemos a meter las fichas dentro de la bolsa inmediatamente después de haberlas sacado, se denomina como una muestra <strong><em>con reemplazo</em></strong>. La diferencia entre este caso y el primero es que es posible observar al mismo elemento de la población varias veces (en este caso la misma ficha), tal como se ilustra en la Figura <a href="estimation.html#fig:srs2">2.3</a>.</p>
<p>Por lo general, la mayoría de los experimentos que veamos en ciencias de la educación tienden a tomar muestras sin reemplazo, ya que la misma persona no puede participar en el experimento dos veces. Sin embargo, una gran parte de la teoría estadística se basa en el supuesto de que los datos surgen de una muestra aleatoria simple <em>con</em> reemplazo. En la vida real, esto rara vez importa. Si la población de interés es grande, la diferencia entre el muestreo con y sin reemplazo es demasiado pequeña como para preocuparnos. Sin embargo, la diferencia que existe entre muestras aleatorias simples y muestras sesgadas no es algo no es algo que podemos ignorar tan facilmente.</p>
</div>
<div id="la-mayoria-de-las-muestras-no-son-muestras-aleatorias-simples" class="section level3">
<h3><span class="header-section-number">2.1.3</span> La mayoría de las muestras no son muestras aleatorias simples</h3>
<p>Si miras la lista anterior de posibles poblaciones, te darás cuenta que es casi imposible obtener una muestra aleatoria simple de la mayoría de esas poblaciones de interés. Cuando hacemos experimentos con estudiantes universitarios, el obtener una verdadera muestra aleatoria de estos estudiantes los podemos considerar como un milagro menor, aunque al final se trate de una población muy específica a partir de la cual generalizar. Mencionaré brevemente algunos de los otros tipos de muestreo que existen y que solemos encontrar con frecuencia:</p>
<ul>
<li><p><em>Muestreo estratificado</em>. Supongamos que tu población está (o puede estar) dividida en varias subpoblaciones o <em>estratos</em> diferentes. Quizás sea porque estás realizando un estudio en varios paises diferentes, por ejemplo. En lugar de intentar tomar una muestra aleatoria de toda la población en su conjunto, recolectamos una muestra aleatoria de cada una de las subpoblaciones o estratos. El muestreo estratificado suele ser más fácil de llevar a cabo que el muestreo aleatorio simple, especialmente cuando la población ya está dividida en los distintos estratos. También puede ser más eficiente que el muestreo aleatorio simple, especialmente cuando algunas de las subpoblaciones son raras o poco frecuentes. Por ejemplo, en el estudio de la esquizofrenia, resulta más sencillo dividir la población en dos estratos (con-esquizofrenia y sin-esquizofrenia) y adquirir una muestra de cada grupo. Si seleccionaramos personas al azar, obtendríamos tan pocas personas con esquizofrenia en la muestra que el estudio resultaría inútil.</p></li>
<li><p><em>Muestreo de bola de nieve</em>. Es una técnica que es especialmente útil cuando se toman muestras de una población “oculta” o de difícil acceso, y es especialmente común en las ciencias sociales. Por ejemplo, supongamos que los investigadores quieren realizar una encuesta de opinión a personas VIH positivo. Es posible que el equipo de investigación solo tenga los datos de contacto de algunas personas VIH positivo, por lo que la encuesta comienza pidiéndoles a esas personas que participen (etapa 1). Al final de la encuesta, se pide a los participantes que proporcionen los datos de contacto de otras personas que podrían querer participar. En la etapa 2, se encuesta a estos nuevos contactos. El proceso continúa hasta que los investigadores obtengan datos suficientes. La gran ventaja del muestreo de bola de nieve es que es capaz de proporcionar datos en situaciones que de otro modo serían imposibles de obtener. Desde el punto de vista estadístico, la principal desventaja es que la muestra es altamente no aleatoria y no aleatoria en formas que son difíciles de abordar.</p></li>
<li><p><em>Muestreo de conveniencia</em>. En este tipo de muestreo las muestras se eligen de una forma conveniente para el investigador, sin que exista una selección al azar a partir de la población de interés. El muestreo de bola de nieve es un tipo de muestreo de conveniencia, pero hay muchos otros. Un ejemplo son los estudios que se basan en estudiantes de universitarios. Estas muestras generalmente no son aleatorias desde dos puntos de vista: en primer lugar, depender de una muestra de estudiantes universitarios significa automáticamente que estos datos están restringidos a una sola subpoblación. En segundo lugar, los estudiantes suelen elegir los estudios en los que participan, por lo que la muestra es un subconjunto de estudiantes autoseleccionado, no un subconjunto seleccionado al azar. En general, la mayoría de los estudios incluyen muestras de conveniencia de una forma u otra. A veces, puede suponer una limitación en la interpretación de los resultados, pero no siempre.</p></li>
</ul>
</div>
<div id="cuanto-importa-si-no-se-tiene-una-muestra-aleatoria-simple" class="section level3">
<h3><span class="header-section-number">2.1.4</span> ¿Cuánto importa si no se tiene una muestra aleatoria simple?</h3>
<p>Hemos visto que en muchos casos no es posible recolectar muestras aleatorias simples. ¿Eso qué impacto tiene? Un ejemplo de ese impacto lo podemos apreciar con la diferencia que existe entre las Figuras <a href="estimation.html#fig:srs1">2.1</a> y <a href="estimation.html#fig:brs">2.2</a>. Sin embargo, no es tan malo como parece. Algunos tipos de muestras sesgadas no representan ningún problema. Por ejemplo, cuando utilizamos el muestreo estratificado, realmente sabemos <em>cuál</em> es el sesgo ya que lo hemos creado deliberadamente, con la intención de <em>aumentar</em> la efectividad de su estudio, y existen técnicas estadísticas que podemos utilizar para ajustar estos sesgos que hemos introducido. En estos casos, por lo tanto, no tenemos un problema.</p>
<p>Sin embargo, es importante recordar que el muestreo aleatorio es un medio para un fin, no el fin en sí mismo. Supongamos que recolectamos una muestra de conveniencia y, como tal, podemos asumir que está sesgada. Un sesgo en el método de muestreo solo es un problema si nos hace sacar conclusiones equivocadas. Desde esta perspectiva, podemos afirmar que no necesitamos que la muestra sea aleatoria en <em>todos</em> los aspectos: necesitamos que sea aleatoria con respecto al fenómeno de interés que buscamos estudiar. Supongamos que estoy haciendo un estudio sobre la capacidad de atención sostenida en niños de 6 años. En el estudio 1, tengo la capacidad de tomar muestras al azar de todos los niños de 6 años del mundo actualmente vivos, con una pequeña excepción: sólo puedo incluir niños nacidos en lunes. En el estudio 2, puedo tomar una muestra al azar de la población española. Con estos estudios quiero generalizar mis resultados a la población de todos los niños de 6 años. ¿Qué estudio es mejor? La respuesta, obviamente, es el estudio 1. ¿Por qué? Porque no tenemos ninguna razón para pensar que “nacer en lunes” influye en la capacidad de atención sostenida. Por otro lado, puedo pensar en varias razones por las que “ser español” podría ser importante. España es un país rico e industrializado con un sistema educativo muy desarrollado. Las personas que crecieron con este sistema habrán tenido experiencias de vida mucho más similares a las experiencias de vida de las personas que diseñaron las pruebas de capacidad de atención sostenida. Esta experiencia compartida podría traducirse fácilmente en creencias similares sobre cómo se debe “realizar una prueba”, entre otras razones. Este tipo de características son importantes y podrían, por ejemplo, llevar a una imagen engañosa de lo que es la capacidad atención sostenida.</p>
<p>Existe un reflexión clave oculta en esta discusión. Al diseñar estudios, es importante pensar en la población de interés y en esforzarse por elegir un método de muestreo que sea apropiado para esa población. En la práctica, muchas veces nos veremos obligados a utilizar una “muestra de conveniencia” (por ejemplo, estudiantes de unos pocos centros), pero deberíamos, al menos, dedicar un tiempo a pensar en los riesgos e implicaciones de esta práctica.</p>
</div>
<div id="parametros-poblacionales-y-estadisticos-muestrales" class="section level3">
<h3><span class="header-section-number">2.1.5</span> Parámetros poblacionales y estadísticos muestrales</h3>
<p>Hasta ahora hemos estado hablando de poblaciones como lo haría un científico. Para un educador, una población puede ser un grupo de niños. Para un ecologista, una población puede ser un grupo de osos. En la mayoría de los casos, las poblaciones son cosas concretas que realmente existen en el mundo real. Los estadísticos, sin embargo, tienen un interés dual. Por un lado, <em>están</em> interesados en los datos del mundo real de la misma forma que los científicos. Por otro lado, también operan en el ámbito de la abstracción pura como lo hacen los matemáticos. En consecuencia, la teoría estadística puede ser un poco abstracta cuando define una población. Para ello, los estadísticos operacionalizan el concepto de “población” en términos de objetos matemáticos los cuales ya conocemos: se llaman distribuciones de probabilidad.</p>
<p>La idea es muy simple. Digamos que estamos hablando (otra vez) de puntajes de coeficiente intelectual (CI). Para un educador, la población de interés es un grupo de humanos reales que tienen puntajes de CI. Un estadístico “simplifica” esto al definir operativamente a la población como la distribución de probabilidad representada en la Figura <a href="estimation.html#fig:IQdista">2.4</a>. Las pruebas de CI están <em>diseñadas</em> de tal forma que la media sea 100, que la desviación estándar sea 15 y que la distribución de los puntajes sea normal. Estos valores se denominan <strong><em>parámetros poblacionales</em></strong> porque son característicos de toda la población. Es decir, decimos que la media de la población <span class="math inline">\(\mu\)</span> es 100, y la desviación estándar de la población <span class="math inline">\(\sigma\)</span> es 15.</p>
<div class="figure"><span id="fig:IQdista"></span>
<img src="FdI2_files/figure-html/IQdista-1.png" alt="Distribución poblacional de los puntajes de CI." width="672" />
<p class="caption">
Figure 2.4: Distribución poblacional de los puntajes de CI.
</p>
</div>
<div class="figure"><span id="fig:IQdistb"></span>
<img src="FdI2_files/figure-html/IQdistb-1.png" alt="Muestra con 100 observaciones provenientes de la distribución poblacional previa." width="672" />
<p class="caption">
Figure 2.5: Muestra con 100 observaciones provenientes de la distribución poblacional previa.
</p>
</div>
<pre><code>## [1] &quot;n= 10 mean= 105.532125293626 sd= 14.1255957708477&quot;</code></pre>
<p>Supongamos que hacemos un experimento. Seleccionamos 100 personas al azar para que elaboren nuestro test de CI, lo cual me dará una muestra aleatoria de la población. Mi muestra consistirá en una serie de números como estos:</p>
<pre><code>                          106 101 98 80 74 ... 107 72 100</code></pre>
<p>Estos puntajes forman parte de una muestra extraída de una población con distribución normal, media de 100 y desviación estándar de 15. Si trazamos un histograma de esta muestra, obtendremos algo como el que se muestra en la Figura <a href="estimation.html#fig:IQdistb">2.5</a>. Podemos ver que el histograma tiene una forma <em>aproximadamente</em> normal, pero aún queda como una aproximación burda de la verdadera distribución de la población que se muestra en la Figura <a href="estimation.html#fig:IQdista">2.4</a>. Si calculamos la media muestral, obtendremos un número que está bastante cerca de la media de la población 100, pero no es idéntico. En este caso, vemos que las personas de mi muestra tienen un CI medio de 98,5 y la desviación estándar de sus puntuaciones de CI es de 15,9. Estos <strong><em>estadísticos muestrales</em></strong> nos presentan una descripción de nuestro conjunto de datos y, aunque son bastante similares a los valores reales de población, no son iguales. En general, los estadísticos muestrales son lo que podemos calcular a partir de un conjunto de datos mientras que los parámetros poblacionales son las cosas sobre las que deseamos aprender. Más adelante, hablaremos sobre cómo podemos estimar los parámetros poblacionales utilizando sus estadísticos muestrales (Sección <a href="estimation.html#pointestimates">2.4</a>) así como qué tan seguros estamos de esos estimadores (Sección <a href="estimation.html#ci">2.5</a>) pero antes necesitamos conocer algunos conceptos adicionales sobre la teoría de muestreo.</p>
</div>
</div>
<div id="lawlargenumbers" class="section level2">
<h2><span class="header-section-number">2.2</span> La ley de los grandes números</h2>
<p>En la sección anterior vimos los resultados de un experimento ficticio con un tamaño de muestra de <span class="math inline">\(N=100\)</span>. Los resultados fueron algo alentadores: la media real de la población es 100,,mientras que la media muestral fue de 98.5, una aproximación razonable. En muchos estudios científicos, este nivel de precisión es perfectamente aceptable, pero existen situaciones en las que nos gustaría ser bastante más precisos. Si queremos que nuestros estadísticos muestrales se acerquen más a los parámetros poblacionales, ¿qué podemos hacer al respecto?</p>
<p>La respuesta lógica sería recolectar más datos. Supongamos que hacemos un experimento más grande, en el cual medimos el CI de 10,000 personas. Si entrás <a href="https://leudave.shinyapps.io/sampling/">aquí</a> podrás hacer una simulación. El histograma de esta simulación se muestra en la Figura <a href="estimation.html#fig:IQdistc">2.6</a>. Una inspección rápida nos revelará que una muestra de mayor tamaño representa una mejor aproximación a la distribución poblacional real, especialmente si la comparamos con la muestra más pequeña. Esto también se ve reflejado en los estadísticos muestrales: el CI medio de la muestra grande es de 99.9 y su desviación estándar es de 15.1. Estos valores son muy cercanos a los valores reales de la población.</p>
<div class="figure"><span id="fig:IQdistc"></span>
<img src="FdI2_files/figure-html/IQdistc-1.png" alt="Muestra con 10,000 observaciones provenientes de la distribución poblacional previa." width="672" />
<p class="caption">
Figure 2.6: Muestra con 10,000 observaciones provenientes de la distribución poblacional previa.
</p>
</div>
<p>Con esto, podemos observar algo que parece obvio: entre más datos tengamos, mejores resultados obtendremos. Esta intuición tan evidente que compartimos todos, los estadísticos la definen como la <strong><em>ley de los grandes números</em></strong>. La ley de los grandes números es una ley matemática que aplica a muchos estadísticos muestrales, pero la forma más sencilla de entenderla es a través de la ley aplicada a las medias. Cuando se aplica a la media muestral, la ley de los grande números nos dice que conforme aumenta el tamaño de muestra, el valor de la media muestral se acercará al valor de la media poblacional real. O, para ser más precisos, conforme el tamaño muestral se aproxima al infinito (escrito como <span class="math inline">\(N \rightarrow \infty\)</span>) la media nuestral se aproximará a la media poblacional (<span class="math inline">\(\bar{X} \rightarrow \mu\)</span>).<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a></p>
<p>Espero que quede patente la importancia de la ley de los grandes números como una herramienta elemental en la teoría estadística. Esta ley de los grandes números es nuestro argumento para justificar nuestra creencia de que recolectar cada vez más y más datos nos acercará a la verdad. Para cualquier conjunto de datos, los estadísticos muestrales que calculemos estarán equivocados, pero la ley de los grandes números nos dice que si seguimos recolectando datos esos estadísticos muestrales tenderán a a acerca más y más a los parámetros poblacionales reales.</p>
</div>
<div id="samplesandclt" class="section level2">
<h2><span class="header-section-number">2.3</span> Distribuciones muestrales y el teorema del límite central</h2>
<p>La ley de los grandes números es una herramienta muy poderosa, pero no será suficiente para responder a todas nuestras preguntas. Entre otras cosas, lo que nos da esta ley es una “garantía a largo plazo”. A largo plazo, si pudiéramos recolectar una cantidad infinita de datos, la ley de los grandes números nos garantiza que los estadísticos muestrales serán correctos.</p>
<p>Sin embargo, esta “garantía a largo plazo” es de poca utilidad en la vida real: no basta con decir que <em>con el tiempo</em> llegaremos a la respuesta correcta cuando calculemos la media muestral. Saber que un conjunto de datos infinitamente largo me dará el valor exacto de la media poblacional es inconciliable con el <em>hecho</em> de que mi conjunto de datos tiene un tamaño de muestra de <span class="math inline">\(N=100\)</span>. En la vida real, tenemos que saber algo más sobre el comportamiento de la media muestral de una muestra modesta como la nuestra.</p>
<div id="samplingdists" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Distribución muestral de la media</h3>
<p>Abandonemos por un momento la idea de tener tamaños de muestra de 10,000 y pensemos en un experimento más modesto. Esta vez extraemos una muestra de <span class="math inline">\(N=5\)</span> personas y medimos su CI. Este es el resultado:</p>
<pre><code>90  82  94  99 110</code></pre>
<p>El CI medio de esta muestra es exactamente 95. Esta muestra nos revela un valor mucho menos preciso que en el experimento previo. Ahora imagina que decides <strong><em>replicar</em></strong> este mismo experimento. Es decir, quieres repetir el mismo procedimiento de tal forma que selecciones una nueva muestra aleatoria de 5 personas y obtener su CI una vez más. Estos son los CI de nuestra nueva muestra:</p>
<pre><code>78  88 111 111 117</code></pre>
<p>Al calcular la media de esta muestra vemos que es de 101. Si repetimos el experimento 10 veces más obtendremos los resultados que se muestran en la siguiente Tabla. Con ella podrás ver que la media muestral cambia con cada replicación del experimento.</p>
<table>
<thead>
<tr class="header">
<th align="left">.</th>
<th align="right">P1</th>
<th align="right">P2</th>
<th align="right">P3</th>
<th align="right">P4</th>
<th align="right">P5</th>
<th align="right">Media.Muestral</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Rep 1</td>
<td align="right">90</td>
<td align="right">82</td>
<td align="right">94</td>
<td align="right">99</td>
<td align="right">110</td>
<td align="right">95.0</td>
</tr>
<tr class="even">
<td align="left">Rep 2</td>
<td align="right">78</td>
<td align="right">88</td>
<td align="right">111</td>
<td align="right">111</td>
<td align="right">117</td>
<td align="right">101.0</td>
</tr>
<tr class="odd">
<td align="left">Rep 3</td>
<td align="right">111</td>
<td align="right">122</td>
<td align="right">91</td>
<td align="right">98</td>
<td align="right">86</td>
<td align="right">101.6</td>
</tr>
<tr class="even">
<td align="left">Rep 4</td>
<td align="right">98</td>
<td align="right">96</td>
<td align="right">119</td>
<td align="right">99</td>
<td align="right">107</td>
<td align="right">103.8</td>
</tr>
<tr class="odd">
<td align="left">Rep 5</td>
<td align="right">105</td>
<td align="right">113</td>
<td align="right">103</td>
<td align="right">103</td>
<td align="right">98</td>
<td align="right">104.4</td>
</tr>
<tr class="even">
<td align="left">Rep 6</td>
<td align="right">81</td>
<td align="right">89</td>
<td align="right">93</td>
<td align="right">85</td>
<td align="right">114</td>
<td align="right">92.4</td>
</tr>
<tr class="odd">
<td align="left">Rep 7</td>
<td align="right">100</td>
<td align="right">93</td>
<td align="right">108</td>
<td align="right">98</td>
<td align="right">133</td>
<td align="right">106.4</td>
</tr>
<tr class="even">
<td align="left">Rep 8</td>
<td align="right">107</td>
<td align="right">100</td>
<td align="right">105</td>
<td align="right">117</td>
<td align="right">85</td>
<td align="right">102.8</td>
</tr>
<tr class="odd">
<td align="left">Rep 9</td>
<td align="right">86</td>
<td align="right">119</td>
<td align="right">108</td>
<td align="right">73</td>
<td align="right">116</td>
<td align="right">100.4</td>
</tr>
<tr class="even">
<td align="left">Rep 10</td>
<td align="right">95</td>
<td align="right">126</td>
<td align="right">112</td>
<td align="right">120</td>
<td align="right">76</td>
<td align="right">105.8</td>
</tr>
</tbody>
</table>
<p>Supongamos ahora que decidimos continuar con este procedimiento, replicando el experimento de “5 puntuaciones de CI” una y otra vez. Y cada vez, obtendremos una media muestral diferente, que en el caso de los 10 experimentos que ya hemos hecho corresponderían con los siguientes valores:</p>
<pre><code>                      95.0 101.0 101.6 103.8 104.4 ...</code></pre>
<p>¿Qué pasaría si continuamos y recolectamos 10,000 medias muestrales y trazamos un histograma con ellas? Obtendríamos un resultado como el que vemos en la Figura <a href="estimation.html#fig:sampdistmean">2.7</a>. En esta imagen podemos apreciar que la media muestral de “5 puntuaciones de CI” se encuentra, por lo general, entre 90 y 110. Pero lo más interesante de esta Figura es que demuestra el hecho de que si repetimos el experimento una y otra vez, ¡lo que obtenemos es una <em>distribución</em> de las medias muestrales! Esta distribución recibe un nombre especial en estadística: se le llama <strong><em>distribución muestral de la media</em></strong>.</p>
<p>Las distribuciones muestrales son una idea teórica importante en la estadística, y además, son cruciales si queremos entender cómo se comportan las muestras pequeñas. Por ejemplo, cuando realizamos el primer experimento con 5 puntuaciones de CI, la media muestral fue de 95. Sin embargo, lo que la distribución muestral nos dice en la Figura <a href="estimation.html#fig:sampdistmean">2.7</a>, es que este experimento con 5 puntuaciones no es muy preciso. Si repetimos el experimento muchas veces, la distribución muestral nos dice que podemos esperar que la media muestral esté entre 80 y 120.</p>
<div class="figure"><span id="fig:sampdistmean"></span>
<img src="FdI2_files/figure-html/sampdistmean-1.png" alt="La distribución muestral de la media en el experimento con 5 puntuaciones de CI. Si obtenemos una muestra aleatoria de 5 personas y calculamos la *media* de sus puntajes, obtendremos casi con seguridad un valor entre 80 y 120, aunque existen individuos que tienen un CI mayor de 120 o menor de 80. La línea negra dibuja la distribución poblacional de los puntajes de CI para comparar." width="672" />
<p class="caption">
Figure 2.7: La distribución muestral de la media en el experimento con 5 puntuaciones de CI. Si obtenemos una muestra aleatoria de 5 personas y calculamos la <em>media</em> de sus puntajes, obtendremos casi con seguridad un valor entre 80 y 120, aunque existen individuos que tienen un CI mayor de 120 o menor de 80. La línea negra dibuja la distribución poblacional de los puntajes de CI para comparar.
</p>
</div>
</div>
<div id="existen-distribuciones-muestrales-para-cualquier-estadistico-muestral" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Existen distribuciones muestrales para cualquier estadístico muestral</h3>
<p>Una cosa que debemos tener en cuenta cuando pensemos sobre las distribuciones muestrales es que es posible estimarlos a partir de <em>cualquier</em> estadístico muestral. Por ejemplo, supongamos que en cada una de las veces que replicamos el “experimento con 5 puntajes de CI” también tomamos nota del valor de CI máximo en cada experimento. Esto daría como resultado una serie de número que empezaría de esta forma:</p>
<pre><code>                      110 117 122 119 113 ... </code></pre>
<p>Si hacemos esto una y otra vez obtendremos una distribución muestral muy diferente, concretamente la <em>distribución muestral del valor máximo</em>. La distribución muestral del valor máximo de 5 puntajes de CI se muestra en la Figura <a href="estimation.html#fig:sampdistmax">2.8</a>. No es de sorprender, que si escogemos a 5 personas al azar y seleccionamos a la persona con el puntaje más alto, este tenga un CI superior a la media. Y de hecho, la mayoría de las veces nos encontraremos con puntajes de CI en el rango entre 100 y 140.</p>
<div class="figure"><span id="fig:sampdistmax"></span>
<img src="img/estimation/sampdistmax.png" alt="Distribución muestral del valor máximo de CI" width="471" />
<p class="caption">
Figure 2.8: Distribución muestral del valor máximo de CI
</p>
</div>
</div>
<div id="clt" class="section level3">
<h3><span class="header-section-number">2.3.3</span> El teorema del límite central</h3>
<p>A continuación verás una serie de ilustraciones en las que podremos observar como influye el tamaño de la muestra en las distribuciones muestrales. Estas distribuciones muestrales se han generado a partir 10,000 muestras de datos sobre el CI, donde se ha calculado la media muestral de cada una de esas muestras. Los histogramas muestran la distribución de esas medias muestrales (en otras palabras, son distribuciones muestrales de la media). Cada valor individual de CI fue extraído de una distribución normal con media de 100 y desviación estándar de 15, que se muestra como una línea sólida de color negro.</p>
<div class="figure"><span id="fig:IQsampa"></span>
<img src="FdI2_files/figure-html/IQsampa-1.png" alt="Esta distribución muestral parte de una sola observación (tamaño muestral de 1), de forma que la media muestral es el puntaje de CI de una persona. Como consecuencia, la distribución muestral de la media es idéntica a la distribución poblacional de los valores de CI." width="672" />
<p class="caption">
Figure 2.9: Esta distribución muestral parte de una sola observación (tamaño muestral de 1), de forma que la media muestral es el puntaje de CI de una persona. Como consecuencia, la distribución muestral de la media es idéntica a la distribución poblacional de los valores de CI.
</p>
</div>
<div class="figure"><span id="fig:IQsampb"></span>
<img src="FdI2_files/figure-html/IQsampb-1.png" alt="Cuando aumentamos el tamaño de la muestra a 2, la media de cualquier muestra tiende a acercarse más a la media poblacional que a un puntaje individual de CI, por lo que el histograma (distribución muestral) es un poco más estrecho que el de la distribución de la población." width="672" />
<p class="caption">
Figure 2.10: Cuando aumentamos el tamaño de la muestra a 2, la media de cualquier muestra tiende a acercarse más a la media poblacional que a un puntaje individual de CI, por lo que el histograma (distribución muestral) es un poco más estrecho que el de la distribución de la población.
</p>
</div>
<div class="figure"><span id="fig:IQsampc"></span>
<img src="FdI2_files/figure-html/IQsampc-1.png" alt="Cuando el tamaño de la muestra es de 10 podemos ver que la distribución muestral de la media tiende a organizarse alrededor de la media (real) de la población." width="672" />
<p class="caption">
Figure 2.11: Cuando el tamaño de la muestra es de 10 podemos ver que la distribución muestral de la media tiende a organizarse alrededor de la media (real) de la población.
</p>
</div>
<p>Espero que con esta demostración, tengas un mejor idea de lo que son las distribuciones muestrales, y en particular lo que es la distribución muestral de la media. En esta sección hablaremos de cómo la distribución muestral de la media cambia en función del tamaño muestral. Intuitivamente tú ya conoces la respuesta: si tenemos sólo unas cuantas observaciones, es probable que la media muestral no sea muy precisa. Si replicas este experimento con una muestra pequeña y vuelves a calcular la media obtendrás, casi con seguridad, una respuesta muy diferente. En otras palabras, su distribución muestral es muy ancha. Por otro lado, si replicas un experimento con un tamaño muestral grande y calculas la media muestral varias veces, es muy probable que obtengas la misma respuesta, o al menos muy aproximada, por lo que la distribución muestral será muy estrecha. Esto lo puedes apreciar visualmente con las Figuras <a href="estimation.html#fig:IQsampa">2.9</a>, <a href="estimation.html#fig:IQsampb">2.10</a> y <a href="estimation.html#fig:IQsampc">2.11</a>: entre más grande sea la muestra, más estrecha será la distribución muestral. Podemos cuantificar este efecto si calculamos la desviación estándar de la distribución muestral, mejor conocida como el <strong><em>error estándar</em></strong>. El error estándar de la media se denota como <span class="math inline">\(\sigma\)</span> con el subíndice <span class="math inline">\(\bar{X}\)</span> (o SEM en inglés). Y como puedes ver y confirmar con las figuras, conforme aumenta el tamaño muestral <span class="math inline">\(N\)</span>, el error estándar disminuye.</p>
<p>De momento hemos visto cómo se comportan las distribuciones muestrales de los puntajes de CI, que es un parámetro que tiene una distribución poblacional normal. Pero, ¿qué pasa con aquellos datos que no guardan una distribución normal? Esta es la clave: sin importar la forma de la distribución de la población, si aumentamos <span class="math inline">\(N\)</span>, su distribución muestral siempre será como la que hemos visto con la distribución normal. Por ejemplo, en la Figura <a href="#fig:cltdemo"><strong>??</strong></a> verás que una distribución poblacional que tiene forma de rampa (los valores más altos son los más frecuentes). Si comparas esta forma con la de la distribución normal (la línea sólida negra), podrás confirmar que no se parecen en nada. Si repetimos el mismo procedimiento que hemos hecho anteriormente, y extraemos un número elevado de muestras (10,000) con un tamaño muestral de <span class="math inline">\(N=2\)</span> y calculamos sus medias muestrales, obtendremos la distribución muestral de la media que puedes ver en la Figura <a href="#fig:cltdemob"><strong>??</strong></a>. Esta distribución cambia de forma de manera importante, y aunque no es normal, se aproxima bastante, sobre todo si la comparamos con la distribución poblacional original (Figura <a href="#fig:cltdemoa"><strong>??</strong></a>). Si aumentamos el tamaño muestral a <span class="math inline">\(N=4\)</span>, la distribución muestral de la media se acerca más a una distribución normal (Figura <a href="#fig:cltdemoc"><strong>??</strong></a>, y con un tamaño muestral de <span class="math inline">\(N=8\)</span> esta ya es perfectamente normal. En otras palabras, siempre y cuando el tamaño de tu muestra no sea diminuto, la distribución muestral de la media será normal, ¡sin importar la forma de la distribución poblacional!</p>
<div class="figure"><span id="fig:cltdemo1"></span>
<img src="FdI2_files/figure-html/cltdemo-1.png" alt="Una demostración del teorema del límite central. En el primer panel, tenemos a una población con una distribución no-normal; en los tres paneles siguientes se muestran distribuciones muestrales de la media para muestra de tamaño muestral de 2, 4 y 8, extraídos de la distribución poblacional del primer panel. Como podrás ver, aunque la distribución poblacional original es no-normal, la distribución muestral de la media se acerca mucho a una distribución normal incluso cuando la muestra tiene 4 observaciones." width="672" />
<p class="caption">
Figure 2.12: Una demostración del teorema del límite central. En el primer panel, tenemos a una población con una distribución no-normal; en los tres paneles siguientes se muestran distribuciones muestrales de la media para muestra de tamaño muestral de 2, 4 y 8, extraídos de la distribución poblacional del primer panel. Como podrás ver, aunque la distribución poblacional original es no-normal, la distribución muestral de la media se acerca mucho a una distribución normal incluso cuando la muestra tiene 4 observaciones.
</p>
</div>
<div class="figure"><span id="fig:cltdemo2"></span>
<img src="FdI2_files/figure-html/cltdemo-2.png" alt="Una demostración del teorema del límite central. En el primer panel, tenemos a una población con una distribución no-normal; en los tres paneles siguientes se muestran distribuciones muestrales de la media para muestra de tamaño muestral de 2, 4 y 8, extraídos de la distribución poblacional del primer panel. Como podrás ver, aunque la distribución poblacional original es no-normal, la distribución muestral de la media se acerca mucho a una distribución normal incluso cuando la muestra tiene 4 observaciones." width="672" />
<p class="caption">
Figure 2.13: Una demostración del teorema del límite central. En el primer panel, tenemos a una población con una distribución no-normal; en los tres paneles siguientes se muestran distribuciones muestrales de la media para muestra de tamaño muestral de 2, 4 y 8, extraídos de la distribución poblacional del primer panel. Como podrás ver, aunque la distribución poblacional original es no-normal, la distribución muestral de la media se acerca mucho a una distribución normal incluso cuando la muestra tiene 4 observaciones.
</p>
</div>
<div class="figure"><span id="fig:cltdemo3"></span>
<img src="FdI2_files/figure-html/cltdemo-3.png" alt="Una demostración del teorema del límite central. En el primer panel, tenemos a una población con una distribución no-normal; en los tres paneles siguientes se muestran distribuciones muestrales de la media para muestra de tamaño muestral de 2, 4 y 8, extraídos de la distribución poblacional del primer panel. Como podrás ver, aunque la distribución poblacional original es no-normal, la distribución muestral de la media se acerca mucho a una distribución normal incluso cuando la muestra tiene 4 observaciones." width="672" />
<p class="caption">
Figure 2.14: Una demostración del teorema del límite central. En el primer panel, tenemos a una población con una distribución no-normal; en los tres paneles siguientes se muestran distribuciones muestrales de la media para muestra de tamaño muestral de 2, 4 y 8, extraídos de la distribución poblacional del primer panel. Como podrás ver, aunque la distribución poblacional original es no-normal, la distribución muestral de la media se acerca mucho a una distribución normal incluso cuando la muestra tiene 4 observaciones.
</p>
</div>
<div class="figure"><span id="fig:cltdemo4"></span>
<img src="FdI2_files/figure-html/cltdemo-4.png" alt="Una demostración del teorema del límite central. En el primer panel, tenemos a una población con una distribución no-normal; en los tres paneles siguientes se muestran distribuciones muestrales de la media para muestra de tamaño muestral de 2, 4 y 8, extraídos de la distribución poblacional del primer panel. Como podrás ver, aunque la distribución poblacional original es no-normal, la distribución muestral de la media se acerca mucho a una distribución normal incluso cuando la muestra tiene 4 observaciones." width="672" />
<p class="caption">
Figure 2.15: Una demostración del teorema del límite central. En el primer panel, tenemos a una población con una distribución no-normal; en los tres paneles siguientes se muestran distribuciones muestrales de la media para muestra de tamaño muestral de 2, 4 y 8, extraídos de la distribución poblacional del primer panel. Como podrás ver, aunque la distribución poblacional original es no-normal, la distribución muestral de la media se acerca mucho a una distribución normal incluso cuando la muestra tiene 4 observaciones.
</p>
</div>
<p>Con base en estas figuras, parece que tenemos evidencia suficiente para sustentar las siguientes afirmaciones sobre las distribuciones muestrales de la media:</p>
<ul>
<li>La media de una distribución muestral es igual a la media poblacional</li>
<li>La desviación estándar de una distribución muestral (el error estándar) disminuye conforme aumenta el tamaño muestral</li>
<li>La forma de una distribución muestral adquiere una forma normal o de campana conforme aumenta el tamaño muestral</li>
</ul>
<p>Estas tres afirmaciones que hemos deducido, pueden ser comprobadas a través de un teorema muy famoso en estadística, conocido como el <strong><em>teorema del límite central</em></strong>. Entre otras cosas, el teorema del límite central nos dice que si una distribución poblacional tiene una media <span class="math inline">\(\mu\)</span> y una desviación estándar <span class="math inline">\(\sigma\)</span>, entonces la distribución muestral de la media también tendra una media <span class="math inline">\(\mu\)</span> y un error estándar de la media:</p>
<p><span class="math display">\[
\mbox{SEM} = \frac{\sigma}{ \sqrt{N} }
\]</span> Ya que en esta fórmula se divide la desviación estándar de la población <span class="math inline">\(\sigma\)</span> por la raíz cuadrada del tamaño muestral <span class="math inline">\(N\)</span>, el error estándar disminuye conforme aumenta el tamaño muestral. También nos dice que la forma de la distribución muestral se vuelve normal.<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a></p>
<p>Este resultado es útil por muchas razones. Nos dice porqué los experimentos con un tamaño muestral más grande son más confiables que aquellos con muestras pequeñas, además de darnos una fórmula para el error estándar que nos permite cuantificar <em>qué tanto</em> más confiable es ese experimento. Nos dice que porque la distribución normal, es… <em>normal</em>. Cuando hacemos un experimento, muchas de las cosas que medimos son en realidad un promedio de muchas otras medidas (por ejemplo, la inteligencia “general” que mide el CI es un promedio de un gran número de habilidades “específicas”), y cuando eso pasa, la cantidad promediada debe seguir una distribución normal. Es por esta ley matemática que la distribución normal aparace con tanta frecuencia en los datos que recogemos del mundo real.</p>
</div>
</div>
<div id="pointestimates" class="section level2">
<h2><span class="header-section-number">2.4</span> Estimando parámetros poblacionales</h2>
<p>En todos los ejemplos anteriores sobre el CI, hemos asumido que conocíamos los parámetros poblacionales. Los tests que miden el CI están <em>diseñados</em> para tener una media de 100 y una desviación estándar de 15: cuando se estudia el CI en una población, se obtienen datos de una muestra muy grande y después se “ajustan” los resultados de forma que la media sea de 100. Esto nos sirve para recordar que una media es representativa únicamente de su población. En ocasiones podremos encontrar “normas” que permiten aplicar esos parámetros en otras poblaciones diferentes (por ejemplo, grupos de edad diferente, nacionalidades, etc.).</p>
<p>Supongamos que ahora queremos explorar el efecto que tiene la contaminación ambiental en el rendimiento académico a través del CI. Para ello obtendremos y compararemos los puntajes de CI de estudiantes de una ciudad con altos índices de contaminación -Albacete- y otra con baja contaminación ambiental -Vitoria- (evidentemente, existen muchos otros factores que pueden influir en el puntaje final de CI). Independientemente de la ciudad que escojamos, no podemos <em>asumir</em> que la media de su población es de 100. No se ha creado una “norma” que se aplique al nivel de contaminación ambiental de las ciudades y su relación con el CI. Por ello, tendremos que <strong><em>estimar</em></strong> los parámetros de la población a partir de una muestra.</p>
<div id="estimando-la-media-poblacional" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Estimando la media poblacional</h3>
<p>Supongamos que vamos a Albacete y conseguimos los puntajes de CI de una muestra de 100 amables albaceteños. Obtenemos que el puntaje medio de esas personas es de <span class="math inline">\(\bar{X}=98.5\)</span>. Entonces, ¿cuál la media real del CI para la población entera de Albacete? Evidentemente, no conocemos la respuesta a esa pregunta. Podría ser <span class="math inline">\(97.2\)</span>, pero también <span class="math inline">\(103.5\)</span>. Nuestra muestra no es lo suficientemente grande como para darnos una respuesta definitiva. Sin embargo, si tuviera que apostar, diría que es <span class="math inline">\(98.5\)</span>. Esta es la esencia de la estimación estadística: dar tu mejor predicción.</p>
<p>En este ejemplo, estimar este parámetro de la población es muy sencillo. Calculamos la media muestral, y utilizo este mismo resultado como el <strong><em>estimador de la media poblacional</em></strong>. En la siguiente sección explicaré la justificación estadística para esta respuesta que parece intuitiva. Por lo pronto, lo que debes reconocer es que, conceptualmente, la media muestral y el estimador de la media poblacional son cosas diferentes. Un estadístico muestral es una descripción de los datos, mientras que un estimador es una predicción sobre la población. Con esto en mente, los estadísticos utilizan una notación diferente para referirse a cada una de ellas. Así, mientras que la media poblacional se denota como <span class="math inline">\(\mu\)</span>, el estimador de la media poblacional utiliza <span class="math inline">\(\hat\mu\)</span> (recuerda que para referirnos a la media muestral usamos <span class="math inline">\(\bar{X}\)</span>). Sin embargo, en muestras simples aleatorias, el estimador de la media poblacional es idéntico a la media muestral: si obtenemos una media muestral de <span class="math inline">\(\bar{X} = 98.5\)</span>, entonces mi estimador de la media poblacional será también de <span class="math inline">\(\hat\mu = 98.5\)</span>. Esta tabla nos ayudará a guardar el registro:</p>
<table>
<thead>
<tr class="header">
<th align="left">Simbolo</th>
<th align="left">Valor</th>
<th align="left">Lo.conocemos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(\bar{X}\)</span></td>
<td align="left">Media muestral</td>
<td align="left">Sí, lo calculamos a partir de datos</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\mu\)</span></td>
<td align="left">Media poblacional</td>
<td align="left">Casi nunca</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\hat{\mu}\)</span></td>
<td align="left">Estimador de la media poblacional</td>
<td align="left">Sí, idéntico a la media muestral</td>
</tr>
</tbody>
</table>
</div>
<div id="estimando-la-desviacion-estandar-poblacional" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Estimando la desviación estándar poblacional</h3>
<p>De momento, la estimación parece algo sencillo, por lo que te preguntarás porqué te hecho leer todo eso sobre la teoría de muestreo. En el caso de la media, nuestro estimador de la media poblacional <span class="math inline">\(\hat\mu\)</span> resulta ser idéntico a la media muestral <span class="math inline">\(\bar{X}\)</span>. Sin embargo, esto no aplica para todos los estadísticos muestrales. Como ejemplo, veamos como se construye el <strong><em>estimador de la desviación estándar poblacional</em></strong>, cuya notación es <span class="math inline">\(\hat\sigma\)</span>. Si seguimos el mismo razonamiento que con el estimador de la media poblacional <span class="math inline">\(\hat\mu\)</span>, cogeríamos a la desviación estándar muestral como nuestro estimador. Esto nos dará una respuesta aproximadamente correcta, pero no del todo.</p>
<p>Veamos porqué. Supongamos que tenemos una muestra de puntajes de CI que contiene una única observación. Este único puntaje es de 99, por lo que tendremos la siguiente muestra:</p>
<pre><code>99</code></pre>
<p>Esta es una muestra perfectamente legítima, aunque tenga un tamaño de muestra de <span class="math inline">\(N=1\)</span>. Esta muestra tiene una media de 99, y al no haber ninguna otra observación en esta muestra, no existe dispersión de datos y por lo tanto tenemos una desviación estándar muestral de 0. Como descripción de una <em>muestra</em> esto es válido: la muestra contiene una sola observación y por lo tanto no hay variabilidad o dispersión dentro de la muestra. En este caso, decir que tenemos una desviación estándar muestral de <span class="math inline">\(s = 0\)</span> es correcto. Pero si utilizamos este valor como estimador de la desviación estándar <em>poblacional</em> parece no tener sentido. No vemos variabilidad en esta <em>muestra</em> simplemente porque ¡la muestra es tan pequeña que no puede mostrar variabilidad! Por lo tanto, si tenemos un tamaño muestral de <span class="math inline">\(N=1\)</span>, “no tenemos ni idea” del estimador de la desviación estándar poblacional.</p>
<p>Observa como en este caso <em>no</em> has tenido la misma intuición que con la media muestral y su estimador. Aunque tengamos una media de 99 a partir de una única observación, es un valor <em>plausible</em>, y nos permite al menos, hacer una predicción.</p>
<p>Vamos a dar un paso más en este ejemplo. Supongamos que ahora recolecto una segunda observación. Mi muestra tiene ahora <span class="math inline">\(N=2\)</span> puntajes de CI, que son los siguientes:</p>
<pre><code>99, 101</code></pre>
<p>Esta vez, la muestra es lo <em>suficientemente</em> grande para que podamos observar algo de variabilidad en ella: dos observaciones es el número mínimo necesario para observar cualquier variabilidad. Para esta nueva muestra, la media muestral es de <span class="math inline">\(\bar{X}=100\)</span>, y su desviación estándar es de <span class="math inline">\(s=1\)</span>. ¿Qué intuiciones o suposiciones podemos hacer de la población? Nuevamente, la mejor predicción que podemos hacer es con la media muestral: si tuviéramos que adivinar, diríamos que la media poblacional es de 100. ¿Y que hay de la desviación estándar? Aquí es un poco más complicado. La desviación estándar muestral está basada únicamente en dos observaciones, y es probable que con esto no hemos dado a la población “suficiente oportunidad” para mostrar cual es su variabilidad real. No es que simplemente sospechemos que utilizar este valor como estimador sea un <em>error</em>: después de todo, con dos observaciones esperamos que <em>esté</em> equivocado en cierto grado. El problema es que este error sea <em>sistemático</em>. Específicamente, sospechamos que la desviación estándar muestral sea menor que desviación estándar poblacional.</p>
<div class="figure"><span id="fig:sampdistsd"></span>
<img src="img/estimation/samplingDistSampleSD.png" alt="Distribución muestral de la desviación estándar del experimento con &quot;dos puntajes de CI&quot;. La media real poblacional es de 15 (línea punteada), pero como puedes ver en el histograma, la mayor parte de los experimentos producirán un valor de desviación estándar muestral mucho más pequeño. En promedio, este experimento daría como resultado una desviación estándar muestral de sólo 8.5, muy por debajo del valor real. En otras palabras, la desviación estándar muestral es un estimador *sesgado* de la desviación estándar poblacional." width="348" />
<p class="caption">
Figure 2.16: Distribución muestral de la desviación estándar del experimento con “dos puntajes de CI”. La media real poblacional es de 15 (línea punteada), pero como puedes ver en el histograma, la mayor parte de los experimentos producirán un valor de desviación estándar muestral mucho más pequeño. En promedio, este experimento daría como resultado una desviación estándar muestral de sólo 8.5, muy por debajo del valor real. En otras palabras, la desviación estándar muestral es un estimador <em>sesgado</em> de la desviación estándar poblacional.
</p>
</div>
<p>Aunque esta intuición pueda ser correcta, sería importante poder demostrarla. Si calculamos <em>la distribución muestral de la desviación estándar</em> para nuestro experimento de <span class="math inline">\(N=2\)</span> puntajes de CI, veremos que el promedio de esas distribuciones estándar <em>muestrales</em> es de tan sólo 8.5 (puedes ver esta distribución en la Figura <a href="estimation.html#fig:sampdistsd">2.16</a>), muy por debajo de la desviación estándar poblacional de 15. Observa que esta distribución es muy diferente a la distribución muestral de la media que vimos en la Figura <a href="estimation.html#fig:IQsampb">2.10</a>. En ella, la media poblacional es de 100, y el promedio de las medias muestrales también es de 100.</p>
<p>Ahora extendamos un poco más esta simulación. En lugar de limitarnos a calcular la distribución muestral de la desviación de muestras de tamaño <span class="math inline">\(N=2\)</span>, repitamos este ejercicio con tamaños muestrales del 1 al 10. Si graficamos como cambia el promedio de las medias muestrales y las desviaciones estándar muestrales en función del tamaño muestral, obtendremos lo que se enseña en la Figura <a href="estimation.html#fig:estimatorbias">2.17</a>. En la parte izquierda (a) vemos graficada los promedios de las medias muestrales y en la parte izquierda los promedios de las desviaciones estándar. Ambas gráficas son diferentes: <em>en promedio</em>, la media muestral es igual a la media poblacional. Esto lo convierte en un <strong><em>estimador insesgado</em></strong>, y es el motivo por el cual la media muestral es el mejor estimador de la media poblacional. En la parte derecha (b), vemos una gráfica distinta: <em>en promedio</em>, la desviación estándar muestral <span class="math inline">\(s\)</span> es <em>menor</em> que la desviación estándar poblacional <span class="math inline">\(\sigma\)</span>. Esto lo convierte en un <strong><em>estimador sesgado</em></strong>. En otras palabras, si queremos hacer nuestra mejor “predicción” <span class="math inline">\(\hat\sigma\)</span> del valor de la desviación estándar poblacional <span class="math inline">\(\sigma\)</span>, podríamos hacerlo aumentando el tamaño de la desviación estándar muestral <span class="math inline">\(s\)</span>.</p>
<div class="figure"><span id="fig:estimatorbias"></span>
<img src="img/estimation/biasMeanSD.png" alt="Demostración del hecho de que la media muestral es un estimador insesgado de la media poblacional (a), mientras que la desviación estándar es un estimador sesgado de la desviación estándar poblacional (b). *En promedio*, la media muestral es 100, independientemente del tamaño muestral (a). Sin embargo, la desviación estándar muestral es sistemáticamente menor que la desviación estándar poblacional (b), sobre todo con tamaños de muestra pequeños." width="806" />
<p class="caption">
Figure 2.17: Demostración del hecho de que la media muestral es un estimador insesgado de la media poblacional (a), mientras que la desviación estándar es un estimador sesgado de la desviación estándar poblacional (b). <em>En promedio</em>, la media muestral es 100, independientemente del tamaño muestral (a). Sin embargo, la desviación estándar muestral es sistemáticamente menor que la desviación estándar poblacional (b), sobre todo con tamaños de muestra pequeños.
</p>
</div>
<p>Arreglar este error sistemático es muy sencillo. Primero, recordemos la fórmula de la desviación estándar poblacional: <span class="math display">\[
\sigma = \sqrt\frac{\sum_{i=1}^N (X_i - \bar{X})^2}{N} 
\]</span> Sólo hace falta un pequeño cambio para corregir ese error sistemático. Lo único que tenemos que hacer dividir por <span class="math inline">\(N-1\)</span> en lugar de por <span class="math inline">\(N\)</span>. Si lo hacemos, obtendremos la siguiente fórmula: <span class="math display">\[
\hat\sigma = \sqrt\frac{\sum_{i=1}^N (X_i - \bar{X})^2}{N-1} 
\]</span> Un último apunte: en la práctica, mucha gente se refiere a <span class="math inline">\(\hat{\sigma}\)</span> (esta última fórmula) como la desviación estándar <em>muestral</em>. Técnicamente, esto es incorrecto: en la desviación estándar <em>muestral</em> se divide únicamente por <span class="math inline">\(N\)</span>. Y es que no son lo mismo, ni conceptualmente ni numéricamente. Uno es una propiedad de una muestra, mientras que el otro es una característica estimada de la población. Sin embargo, lo normal es que nos interesemos por calcular el estimador de la población, por lo que solemos utilizar <span class="math inline">\(\hat\sigma\)</span> en lugar de <span class="math inline">\(s\)</span>. Quizás esta imprecisión se deba a que es más fácil escribir “desviación estándar muestral” que “estimador de la desviación estándar poblacional”. En la práctica, no suele haber mucha diferencia, sin embargo, es importante separar ambos <em>conceptos</em>: no debemos confundir las “características conocidas de tu muestra” con las “predicciones acerca de la población”.</p>
<table>
<thead>
<tr class="header">
<th align="left">Simbolo</th>
<th align="left">Valor</th>
<th align="left">Lo.sabemos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(s\)</span></td>
<td align="left">Desviación estándar muestral</td>
<td align="left">Sí, lo calculamos a partir de datos</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\sigma\)</span></td>
<td align="left">Desviación estándar poblacional</td>
<td align="left">Casi nunca</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\hat{\sigma}\)</span></td>
<td align="left">Estimador de la desviación estándar poblacional</td>
<td align="left">Sí, pero no es igual a la desviación estándar muestral</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="ci" class="section level2">
<h2><span class="header-section-number">2.5</span> Estimando un intervalo de confianza</h2>
<p>Hasta este punto en esta 2ª Unidad, hemos revisado los conceptos básicos de la teoría de muestreo que los estadísticos utilizan para hacer predicciones sobre los parámetros poblacionales a partir de una muestra de datos. Una de las razones por las cuales necesitamos de esta teoría de muestro es que cada conjunto de datos nos deja con un cierto grado de incertidumbre, por lo que nuestros estimadores nunca serán precisos a la perfección. Sin embargo, nosotros somos capaces de <em>cuantificar</em> esa incertidumbre que va implícita en nuestros estimadores. No basta con predecir que el CI medio de mi muestra de estudiantes es de 105; también podemos expresar el grado de certeza que tenemos sobre esa predicción.<br />
Nos gustaría, por ejemplo, decir que tenemos un 95% de probabilidad de que un rango de valores contenga la media real. Esta herramienta existe y recibe el nombre de <strong><em>intervalo de confianza</em></strong> de la media.</p>
<p>Como ya conocemos y entendemos como funcionan las distribuciones muestrales, construir un intervalo de confianza resulta relativamente sencillo. Supongamos que la media real poblacional es <span class="math inline">\(\mu\)</span> y la desviación estándar es <span class="math inline">\(\sigma\)</span>. Hemos terminado un estudio que incluye a <span class="math inline">\(N\)</span> participantes, y el CI medio de esos participantes es de <span class="math inline">\(\bar{X}\)</span>. Por nuestra discusión sobre teorema del límite central (Sección <a href="estimation.html#clt">2.3.3</a>), sabemos que la distribución muestral de la media es aproximadamente normal. También sabemos por nuestra discusión sobre la distribución normal (Sección <a href="probability.html#normal">1.5</a>) que existe un 95% de probabilidad de que una cantidad normalmente distribuida caiga dentro de dos desviaciones estándar alrededor de la media real (es decir, entre los percentiles 2.5 y 97.5). Aunque si vamos al detalle (con la ayuda de nuestra tabla z), vemos que no son dos desviaciones estándar exactamente, sino 1.96, que es el número que utilizaremos de aquí en adelante.</p>
<p>Ahora, recordemos que cuando hablamos de la desviación estándar de una distribución muestral, nos estamos refiriendo al error estándar, en este caso, de la media (SEM). Si juntamos todos estos elementos, podemos decir que existe una probabilidad del 95% de que la media muestral <span class="math inline">\(\bar{X}\)</span> caiga dentro de 1.96 desviaciones estándar de la media poblacional. Matemáticamente lo podemos expresar de la siguiente forma: <span class="math display">\[
\mu - \left( 1.96 \times \mbox{SEM} \right) \ \leq \  \bar{X}\  \leq \  \mu + \left( 1.96 \times \mbox{SEM} \right) 
\]</span> donde el error estándar (SEM) es igual a <span class="math inline">\(\sigma / \sqrt{N}\)</span>. Sin embargo, esto no responde a nuestra pregunta original. La ecuación anterior nos dice lo que podemos esperar de la media muestral, dado que conocemos los parámetros poblacionales. En cambio, lo que nosotros <em>queremos</em> saber es justo lo contrario: queremos conocer qué creer de los parámetros poblacionales, dado lo observado a partir de una muestra. Por lo tanto, podemos aplicar nuestros conocimientos de álgebra y despejar esta ecuación de forma que nos de la respuesta que buscamos: <span class="math display">\[
\bar{X} -  \left( 1.96 \times \mbox{SEM} \right) \ \leq \ \mu  \ \leq  \ \bar{X} +  \left( 1.96 \times \mbox{SEM}\right)
\]</span> Lo que esta nueva ecuación nos dice, es que un rango de valores tiene un 95% de probabilidad de contener la media poblacional <span class="math inline">\(\mu\)</span>. A este rango específico lo conocemos como el <strong><em>intervalo de confianza de 95%</em></strong>, y se denota como <span class="math inline">\(\mbox{CI}_{95}\)</span>. Así, mientras el tamaño de muestra <span class="math inline">\(N\)</span> sea lo suficientemente grande -suficientemente grande para creer que la distribución muestral de la media es normal-, entonces podemos escribir nuestra fórmula del intervalo de confianza de 95% de la siguiente forma: <span class="math display">\[
\mbox{CI}_{95} = \bar{X} \pm \left( 1.96 \times \frac{\sigma}{\sqrt{N}} \right)
\]</span> Es imporante aclarar que no hay nada de especial en el número 1.96; simplemente es el multiplicador para un nivel de confianza del 95% que suele ser el más utilizado cuando se calcula un intervalo de confianza. Dependiendo de las circunstancias, podemos disminuir o aumentar ese nivel de confianza (por ejemplo, un nivel de confianza de 70% nos da un valor de 1.04).</p>
<div id="que-pasa-cuando-no-conocemos-los-parametros-poblacionales" class="section level3">
<h3><span class="header-section-number">2.5.1</span> ¿Qué pasa cuando no conocemos los parámetros poblacionales?</h3>
<p>La fórmula que hemos utilizado para calcular el intervalo de confianza de 95% es aproximadente correcta. Sin embargo, no hemos explorado un detalle importante dentro de esta discusión. La fórmula requiere que usemos el error estándar de la media (SEM), que a su vez requiere que utilicemos la desviación estándar de la población <span class="math inline">\(\sigma\)</span>. No obstante, en la Sección <a href="estimation.html#pointestimates">2.4</a> vimos que, por lo general, nosotros no <em>conocemos</em> los parámetros poblacionales. Como no conocemos el valor verdadero de <span class="math inline">\(\sigma\)</span>, tenemos que usar el estimador de la desviación estandar <span class="math inline">\(\hat{\sigma}\)</span> en su lugar. Esto tiene como consecuencia que tenemos que usar los cuantiles de la distribución <span class="math inline">\(t\)</span> en lugar de los de la distribución normal (valores <span class="math inline">\(z\)</span>); y la elección de ese cuantil depende directamente del tamaño muestral. Si la <span class="math inline">\(N\)</span> es muy grande, obtendremos prácticamente el mismo valor: para un nivel de confianza del 95%, una muestra de tamaño <span class="math inline">\(N=10,000\)</span>, nos da un valor <span class="math inline">\(t\)</span> de 1.96. Pero si la <span class="math inline">\(N\)</span> es pequeña obtendremos un valor <span class="math inline">\(t\)</span> mucho mayor: utilizando el mismo nivel de confianza, pero una muestra con <span class="math inline">\(N=10\)</span>, el valor <span class="math inline">\(t\)</span> es igual a 2.26.</p>
<p>Un valor más grande nos dice que el intervalo de confianza es más ancho, lo cual indica mayor incertidumbre sobre dónde se encuentra la media real poblacional <span class="math inline">\(\mu\)</span>. Cuando utilizamos la distribución <span class="math inline">\(t\)</span> en lugar de la distribución normal, obtenemos números más grandes, lo que indica un mayor grado de incertidumbre. ¿Y esto a que se debe? Se debe simplemente a que el estimador de la desviación estándar poblacional <span class="math inline">\(\hat\sigma\)</span> puede estar equivocado. Si está equivocado, implica que estamos un poco menos seguros sobre la forma de la distribución muestral de la media… y esta incertidumbre se ve reflejada en un intervalo de confianza más ancho.</p>
</div>
<div id="interpretando-un-intervalo-de-confianza" class="section level3">
<h3><span class="header-section-number">2.5.2</span> Interpretando un intervalo de confianza</h3>
<p>Quizás lo más difícil sobre un intervalo de confianza es entender lo que en realidad <em>significa</em>. Cuando vemos por primera vez un intervalo de confianza, el primer instinto es decir “que existe un probabilidad del 95% de que la media real se encuentre dentro del intervalo de confianza”. Sin embargo, esta idea que parece acorde con el sentido común, está equivocada. Esta definición confía fuertemente en las <em>creencias</em> personales sobre el valor de la media poblacional: “yo creo que este valor tiene un 95% de probabilidad de entrar en este rango”. Si recuerdas lo que vimos en la Sección <a href="probability.html#probmeaning">1.2</a>, te darás cuenta que cuando hablamos de creencias personales y confianza, estamos hablando de la estadística Bayesiana. Sin embargo, los intervalos de confianza <em>no</em> son herramientas Bayesianas. Como casi todo lo que hemos visto en este curso, los intervalos de confianza son herramientas <em>frecuentistas</em>, y como tal, debemos adoptar interpretaciones frecuentistas.</p>
<p>Revisemos el concepto de probabilidad frecuentista: para poder hacer declaraciones de probabilidad, tenemos que referirnos a una serie de eventos, y contar las frecuencias de los diferentes tipos de eventos (como cuando lanzamos muchas veces una moneda y contamos el número de caras y de cruces). Desde esta perspectiva, la interpretación del intervalo de confianza de 95% tendrá que ver con la repetición de experimentos o replicación: si replicamos el experimento una y otra vez y calculamos el intervalo de confianza del 95% para cada replicación, entonces el 95% de esos <em>intervalos</em> contendrán la media real poblacional. Esta idea se ilustra en la Figura <a href="estimation.html#fig:cirep">2.18</a>, que muestra 50 intervalos de confianza construidos para un “experimento que mide 10 puntajes de CI” y otros 50 intervalos de confianza para un “experimento que mide 25 puntajes de CI”. En este ejemplo, vemos como exactamente el 95% de los intervalos de confianza contiene a la media real.</p>
<div class="figure"><span id="fig:cirep"></span>
<img src="img/estimation/confIntReplicated.png" alt="Intervalos de confianza de 95%. En la parte superior (a) se muestran 50 replicaciones de un experimento que mide el CI de 10 personas. Los puntos indican la localización de la media muestral, y las líneas indican el intervalo de confianza de 95%. En un 47 de 50 replicaciones, el intervalo de confianza contiene a la media real poblacional (i.e. 100), mientras que tres intervalos no la contienen (marcados con un asterisco). En la parte inferior (b) se muestra una simulación similar, pero con la replicación de un experimento que mide el CI de 25 personas. Observa con los intervalos de confianza son más pequeños con muestras más grandes." width="495" />
<p class="caption">
Figure 2.18: Intervalos de confianza de 95%. En la parte superior (a) se muestran 50 replicaciones de un experimento que mide el CI de 10 personas. Los puntos indican la localización de la media muestral, y las líneas indican el intervalo de confianza de 95%. En un 47 de 50 replicaciones, el intervalo de confianza contiene a la media real poblacional (i.e. 100), mientras que tres intervalos no la contienen (marcados con un asterisco). En la parte inferior (b) se muestra una simulación similar, pero con la replicación de un experimento que mide el CI de 25 personas. Observa con los intervalos de confianza son más pequeños con muestras más grandes.
</p>
</div>
<p>La diferencia clave es que la pretensión Bayesiana es hacer una declaración de probabilidad sobre la media poblacional, lo cual no está permitido bajo una interpretación de la probilidad frecuentista ya que no se puede “replicar” una población. Desde el punto de vista frecuentista, la media poblacional es fija y no se pueden hacer declaraciones de probabilidad sobre ella. Sin embargo, los intervalos de confianza sí que son repetibles, y por lo tanto, podemos replicar experimentos. Así, un frecuentista puede hablar sobre la probabilidad de que el <em>intervalo de confianza</em> (una variable aleatoria) contenga la media poblacional; pero no puede hablar sobre la probabilidad de que la <em>media real poblacional</em> (un evento no repetible) caiga dentro de un intervalo de confianza.</p>
</div>
</div>
<div id="samplesize" class="section level2">
<h2><span class="header-section-number">2.6</span> Estimando el tamaño muestral</h2>
<p>Hasta este punto, hemos aprendido a utilizar las herramientas que nos permiten reducir el nivel de incertidumbre cuando queremos conocer los parámetros de una población a partir de los resultados de una muestra. Sabemos estimar un parámetro poblacional y establecer su intervalo de confianza. También hemos aprendido, gracias a la ley de los grandes números, que el <em>grado de incertidumbre</em> depende particularmente del tamaño de la muestra: mientras tengamos un mayor tamaño muestral, los estimadores se aproximarán más a los parámetros reales poblacionales y sus intervalos de confianza serán más estrechos.</p>
<p>Sin embargo, sabemos que en muchas ocasiones no podremos aspirar a un tamaño muestral tan grande como los que hemos utilizados en nuestors ejemplos. Es habitual que un investigador se vea limitado a recolectar una muestra pequeña por motivos económicos, de accesibilidad, prácticos, o porque simplemente no tiene el tiempo para ello. Por todo esto, espero que entiendas la importancia que tiene calcular el tamaño de una muestra que, nos de resultados de los que cuales nos podamos fiar, y a su vez, no se convierta en una tarea imposible para el investigador.</p>
<p>Por suerte, calcularlo no es muy complicado y podemos reutilizar los conceptos que hemos aprendido en esta Unidad. Para ello, tomemos nuestra fórmula del intervalo de confianza de 95%: <span class="math display">\[
\mbox{CI}_{95} = \bar{X} \pm \left( 1.96 \times \frac{\sigma}{\sqrt{N}} \right)
\]</span> Si te fijas bien, observarás que está fórmula necesita del tamaño muestral <span class="math inline">\(N\)</span> para poder ser resuelta. Para llegar a ella, podemos empezar por separar los elementos que conforman a la fórmula del intervalo de confianza (media muestral y margen de error), y quedarnos con el <strong><em>margen de error</em></strong> (<span class="math inline">\(ME\)</span>) que es el resultado de multiplicar el nivel de confianza (en este caso 1.96), por el error estándar: <span class="math display">\[
ME = 1.96 \times \frac{\sigma}{\sqrt{N}} \
\]</span> A partir de aquí, calcular <span class="math inline">\(N\)</span> es muy sencillo. Si conocemos el resto de elementos que integran la ecuación, podemos despejar <span class="math inline">\(N\)</span> y obtener la siguiente fórmula para el cálculo del <strong><em>tamaño muestral</em></strong>: <span class="math display">\[
N = \left( 1.96 \times \frac{\sigma}{ME} \right)^2
\]</span> Al observar esta fórmula, vemos que nos enfrentamos al mismo problema que tuvimos al calcular el intervalo de confianza: en muchas ocasiones no podremos conocer el valor de la desviación estándar poblacional <span class="math inline">\(\sigma\)</span>. Adicionalmente, tampoco sabemos cuál es nuestro margen de error (<span class="math inline">\(ME\)</span>).</p>
<p>Para resolver el problema con la desviación estándar <span class="math inline">\(\sigma\)</span> contamos con dos opciones. Por un lado, podemos utilizar un valor de desviación estándar <em>aproximado</em>, que puede estar basado en los hallazgos encontrados en poblaciones similares a nuestra población de interés, en la teoría o puede ser simplemente un cálculo conservador que denote el grado de incertidumbre que realmente tenemos sobre esa población. Por otro lado, podemos llevar a cabo un <strong><em>estudio piloto</em></strong>, en el cual recolectemos los datos de una muestra pequeña que nos permitan estimar un media <span class="math inline">\(\bar{X}\)</span> y una desviación estándar muestrales <span class="math inline">\(s\)</span> que después podamos utilizar en el cálculo del tamaño muestral para un estudio más grande.</p>
<p>En el caso del margen de error, la solución es un poco más fácil. Así como el nivel de confianza que se utiliza con más frecuencia es el del 95%, podemos aplicar este mismo criterio para el <span class="math inline">\(ME\)</span>. En investigación se suele utilizar un margen de error de entre el 3% y el 10%, dependiendo de la necesidad o importancia de tener resultados más o menos precisos. Una buena regla general, es utilizar el <strong>5% de la media</strong> como margen de error. De esta forma, aseguramos que los intervalos de confianza que obtengamos a partir de esa muestra sean estrechos y nos permitan esgrimir conclusiones con mayor seguridad.</p>
</div>
<div id="resumen-1" class="section level2">
<h2><span class="header-section-number">2.7</span> Resumen</h2>
<p>En esta Unidad hemos cubierto dos grandes temas. En la primera mitad, hablamos sobre la teoría de muestreo, y en la segunda hemos visto cómo podemos usar la teoría de muestreo para construir estimadores de los parámetros poblacionales. El contenido lo podemos organizar en las siguientes ideas:</p>
<ul>
<li>Ideas básicas sobre las muestras, muestreo y poblaciones (Sección <a href="estimation.html#srs">2.1</a>)</li>
<li>Teoría estadística del muestreo: la ley de los grandes números (Sección <a href="estimation.html#lawlargenumbers">2.2</a>), las distribuciones muestrales y el teorema del límite central (Sección <a href="estimation.html#samplesandclt">2.3</a>).</li>
<li>Estimar medias y desviaciones estándar (Sección <a href="estimation.html#pointestimates">2.4</a>)</li>
<li>Estimar intervalos de confianza (Sección <a href="estimation.html#ci">2.5</a>)</li>
<li>Estimar el tamaño muestral (Sección <a href="estimation.html#samplesize">2.6</a>)</li>
</ul>

</div>
</div>









<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p>Técnicamente, la de ley de los grandes números es aplicable a cualquier estadístico muestral que pueda ser descrito como un promedio de cantidades independiente. La varianza muestral, por ejemplo, puede ser representado como un tipo de promedio y por ello, sujeto a la ley de los grandes números. Sin embargo, el valor mínimo muestral no puede ser interpretado como un promedio de nada, y por tanto, no es gobernado por la ley de los grandes números.<a href="estimation.html#fnref3">↩</a></p></li>
<li id="fn4"><p>Hemos explicado el caso de la media muestral que satisface el teorema del límite central. Sin embargo, existen otros estadísticos muestrales que también lo hacen, y que no revisaremos, al ser esto una introducción.<a href="estimation.html#fnref4">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probability.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["FdI2.pdf", "FdI2.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
